/**
 * Provision a crawler worker node and write a one-time machine token env file.
 *
 * Usage:
 *   npx tsx scripts/provision-crawler-worker.ts
 *   npx tsx scripts/provision-crawler-worker.ts --name local-dev
 *   npx tsx scripts/provision-crawler-worker.ts --force   # create another node even if one exists
 *
 * Writes (gitignored): .crawler-worker.env
 * Does NOT start the Python worker process.
 */
import 'dotenv/config';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createMariaDbAdminDeps } from '../lib/server/crawler/interfaces/compose-mariadb-crawler';
import { AdminCrawlerService } from '../lib/server/crawler/application/admin-crawler-service';
import { pool } from '../lib/db';

const OUT = resolve(process.cwd(), '.crawler-worker.env');

function parseArgs(argv: string[]) {
  let name = 'local-dev';
  let force = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--force') force = true;
    else if (a === '--name' && argv[i + 1]) {
      name = argv[++i];
    } else if (a.startsWith('--name=')) {
      name = a.slice('--name='.length);
    }
  }
  return { name, force };
}

async function main() {
  const { name, force } = parseArgs(process.argv.slice(2));
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL is required');
  }

  const service = new AdminCrawlerService(createMariaDbAdminDeps());
  const existing = await service.listWorkers();

  if (existing.length > 0 && !force) {
    console.log(
      JSON.stringify(
        {
          action: 'provision-crawler-worker',
          skipped: true,
          reason: 'workers already exist; pass --force to create another',
          workers: existing.map((w) => ({
            id: w.id,
            name: w.name,
            lastHeartbeatAt: w.lastHeartbeatAt,
          })),
          envFile: existsSync(OUT) ? OUT : null,
          hint: existsSync(OUT)
            ? 'Reuse existing .crawler-worker.env or revoke + --force to re-issue'
            : 'Token was shown once at provision time; create a new worker with --force if lost',
        },
        null,
        2,
      ),
    );
    await pool.end();
    return;
  }

  const result = await service.provisionWorker(name);
  const controlUrl =
    process.env.CRAWLER_CONTROL_URL
    || `http://127.0.0.1:3000/api/internal/crawler/v1`;

  const tempDir =
    process.env.CRAWLER_TEMP_DIR
    || resolve(process.cwd(), '.crawler-worker-tmp');
  const body = [
    `# Generated by scripts/provision-crawler-worker.ts — DO NOT COMMIT`,
    `# Worker id=${result.worker.id} name=${result.worker.name} credential=${result.credentialId}`,
    `CRAWLER_CONTROL_URL=${controlUrl}`,
    `CRAWLER_WORKER_ID=${result.worker.id}`,
    `CRAWLER_WORKER_TOKEN=${result.token}`,
    `CRAWLER_WORKER_VERSION=${result.worker.version}`,
    `CRAWLER_TEMP_DIR=${tempDir}`,
    '',
  ].join('\n');

  writeFileSync(OUT, body, { encoding: 'utf8', mode: 0o600 });

  console.log(
    JSON.stringify(
      {
        action: 'provision-crawler-worker',
        skipped: false,
        workerId: result.worker.id,
        workerName: result.worker.name,
        credentialId: result.credentialId,
        envFile: OUT,
        controlUrl,
        startHint:
          process.platform === 'win32'
            ? 'set /p= < .crawler-worker.env then: python -m crawler_worker.main  (or use start-crawler-worker script)'
            : 'set -a && source .crawler-worker.env && set +a && python -m crawler_worker.main',
      },
      null,
      2,
    ),
  );
  // Never print the raw token to stdout after write — only path.
  if (process.env.CRAWLER_PRINT_TOKEN === '1') {
    console.error('CRAWLER_WORKER_TOKEN=' + result.token);
  }
  await pool.end();
}

main().catch(async (error) => {
  console.error(error);
  try {
    await pool.end();
  } catch {
    /* ignore */
  }
  process.exit(1);
});
